### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(PVA_VPU50_SCADA)
add_subdirectory(PVA_VPU50_SCADAContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        "vercel.json"
        ".vercel/project.json"
        ".vscode/settings.json"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Qt6::Quick3D
    PVA_VPU50_SCADAplugin
    PVA_VPU50_SCADAContentplugin
    QtQuickDesignerComponents)