### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Scada_control_screen_try_2)
add_subdirectory(Scada_control_screen_try_2Content)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        ".vscode/settings.json"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Scada_control_screen_try_2plugin
    Scada_control_screen_try_2Contentplugin
    QtQuickDesignerComponents)