### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(PVA_VPU50_SCADA)
add_subdirectory(PVA_VPU50_SCADAContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        "vercel.json"
        ".vercel/project.json"
        ".vscode/settings.json"
        "scratch/01_extract_agitator_gif_frames_to_svg/output_frames/agitator_sequence.json"
        "scratch/01_extract_agitator_gif_frames_to_svg/output_frames/rotation_comparison_report.json"
        "scratch/02_extract_mp4_agitator_frames/output_frames/agitator_sequence.json"
        "scratch/03_extract_screen_recording_frames/output_frames/agitator_sequence.json"
        "scratch/04_extract_no_reflection_agitator_frames/agitator_sequence.json"
        "scratch/05_manual_removebg_imported_frames/agitator_sequence.json"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    PVA_VPU50_SCADAplugin
    PVA_VPU50_SCADAContentplugin
    QtQuickDesignerComponents)